-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE MR JOIN REST_REVIEW RR ON MR.MEMBER_ID = RR.MEMBER_ID
WHERE MR.MEMBER_ID = (
    SELECT MEMBER_ID 
    FROM (
        SELECT MEMBER_ID, COUNT(*)
        FROM REST_REVIEW 
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC
        LIMIT 1
    ) AS BEST_REVIEWER
)
ORDER BY REVIEW_DATE, REVIEW_TEXT