-- 코드를 입력하세요
# SELECT *
# FROM CAR_RENTAL_COMPANY_CAR CC JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
# WHERE CAR_TYPE = '세단' AND MONTH(START_DATE) = 10
# ORDER BY CC.CAR_ID DESC

SELECT RH.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
JOIN CAR_RENTAL_COMPANY_CAR CC ON RH.CAR_ID = CC.CAR_ID
WHERE CAR_TYPE = '세단' AND MONTH(START_DATE) = 10
GROUP BY RH.CAR_ID
ORDER BY RH.CAR_ID DESC