SELECT ID, FISH_NAME, LENGTH
FROM (
    SELECT 
        ID, 
        FISH_TYPE, 
        LENGTH,
        ROW_NUMBER() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS LEN_RANK
    FROM FISH_INFO
) AS BF
JOIN FISH_NAME_INFO FN ON BF.FISH_TYPE = FN.FISH_TYPE
WHERE LEN_RANK = 1
ORDER BY ID